### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by drnic1** [Swift-open-source/UltraTabSaver#14]
Thanks for creating this - very useful but struggling to understand how to install. Is there somewhere I can read how to install these files on my Mac? Do I have to load it into xproj and build it and if so some help would be greatly appreciated
Many thanks

**Comment by morsamatias** [comment]
@drnic1  I will create an Install Guide this weekend.

**Comment by drnic1** [comment]
@morsamatias - many thanks you are very generous and I greatly appreciate that

**Comment by morsamatias** [comment]
Hi, I have created this [Installation Guide](https://github.com/Swift-open-source/UltraTabSaver/blob/main/INSTALLATION_GUIDE.md), I hope You find it useful. 
If you have any question please **re open this issue**
