### ISSUE TITLE
Building extension issue

### ISSUE THREAD

**Issue by nikitavoloboev** [Swift-open-source/UltraTabSaver#6]
I cloned the project and signed it to my name in Xcode settings.

However when I then try to run it, I see this:

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/6391776/81193827-2ffdb080-8fbc-11ea-951c-4fd4a1fd5f52.png">

And I am not sure what I should pick here.

**Comment by morsamatias** [comment]
Did you tried to choose Safari?

**Comment by morsamatias** [comment]
Closed because @nikitavoloboev didn't answer
