### ISSUE TITLE
PR: Add Tab Title

### ISSUE THREAD

**Issue by oldzhg** [Swift-open-source/UltraTabSaver#7]
I made some changes to make it easier to find the tab what I wanted with the title.
It looks like this.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/30204608/82240517-220d3f80-996d-11ea-9984-af211d57aa07.png">

**Comment by morsamatias** [comment]
If you want you can create a PR with that Feature.

**Comment by oldzhg** [comment]
I can't add the shortcuts "⌘H". I have created a PR, maybe you can check.

**Comment by morsamatias** [comment]
I close this issue, for more info look at the PR: [https://github.com/Swift-open-source/UltraTabSaver/issues/7](https://github.com/Swift-open-source/UltraTabSaver/issues/7)
